import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/index.module.css";
import Spinner from "@/components/Spinner";

const inter = Inter({ subsets: ["latin"] });

const CalendarPage = () => {
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        ROOOOOOOOOOOOOOOOT
      </main>
    </>
  );
};

export default CalendarPage;
